services:
  jellyfix:
    container_name: jellyfix
    image: ghcr.io/sphexi/jellifinflix:main
    volumes:
      - /share/Media:/media:rw
    environment:
      - CRON_STRING=* * * * *
      - TZ=Europe/Paris
      - JF_API_KEY=
      - JF_URL=
    restart: always
    healthcheck:
      disable: false